# Configuration for Alacritty, the GPU enhanced terminal emulator.

window:
    dimensions:
        columns: 80
        lines: 38
    padding:
        x: 20
        y: 20
    decorations: full
    title: Terminal

font:
    normal:
        family: Mononoki
        style: Regular
    bold:
            style: Bold
    italic:
            style: Italic
    bold_italic:
            style: Bold Italic

    size: 11.0
    offset:
        x: -1
        y: 2
    use_thin_strokes: false

dynamic_title: true

mouse:
    url:
        launcher:
            program: open
            args: []

key_bindings:
    - { key: H,         mods: alt,       chars: "\x1bh"           }
    - { key: J,         mods: alt,       chars: "\x1bj"           }
    - { key: K,         mods: alt,       chars: "\x1bk"           }
    - { key: L,         mods: alt,       chars: "\x1bl"           }

# Base16 OneDark 256 - alacritty color config
# Lalit Magant (http://github.com/tilal6991)
colors:
  # Default colors
  primary:
    background: '0x282c34'
    foreground: '0xabb2bf'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x282c34'
    cursor: '0xabb2bf'

  # Normal colors
  normal:
    black:   '0x282c34'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xe5c07b'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xabb2bf'

  # Bright colors
  bright:
    black:   '0x545862'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xe5c07b'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xc8ccd4'

  indexed_colors:
    - { index: 16, color: '0xd19a66' }
    - { index: 17, color: '0xbe5046' }
    - { index: 18, color: '0x353b45' }
    - { index: 19, color: '0x3e4451' }
    - { index: 20, color: '0x565c64' }
    - { index: 21, color: '0xb6bdca' }
