# Configuration for Alacritty, the GPU enhanced terminal emulator.

window:
    dimensions:
        columns: 80
        lines: 24
    padding:
        x: 40
        y: 40
    decorations: buttonless
    title: Terminal

font:
    normal:
        family: Inconsolata LGC
        style: Regular
    bold:
            style: Bold
    italic:
            style: Italic
    bold_italic:
            style: BoldItalic

    size: 12.0
    use_thin_strokes: false

dynamic_title: true

mouse:
    url:
        launcher:
            program: open
            args: []

key_bindings:
    - { key: Key3,      mods: alt,       chars: "#"               }
    - { key: H,         mods: alt,       chars: "\x1bh"           }
    - { key: J,         mods: alt,       chars: "\x1bj"           }
    - { key: K,         mods: alt,       chars: "\x1bk"           }
    - { key: L,         mods: alt,       chars: "\x1bl"           }
    - { key: F,         mods: Command,   action: ToggleFullscreen }
    # I do not want to accidentally press these:
    - { key: H,         mods: Command,   action: None             }
    - { key: Q,         mods: Command,   action: None             }
    - { key: M,         mods: Command,   action: None             }

# Base16 Monokai 256 - alacritty color config
# Wimer Hazenberg (http://www.monokai.nl)
colors:
  # Default colors
  primary:
    background: '0x272822'
    foreground: '0xf8f8f2'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x272822'
    cursor: '0xf8f8f2'

  # Normal colors
  normal:
    black:   '0x272822'
    red:     '0xf92672'
    green:   '0xa6e22e'
    yellow:  '0xf4bf75'
    blue:    '0x66d9ef'
    magenta: '0xae81ff'
    cyan:    '0xa1efe4'
    white:   '0xf8f8f2'

  # Bright colors
  bright:
    black:   '0x75715e'
    red:     '0xf92672'
    green:   '0xa6e22e'
    yellow:  '0xf4bf75'
    blue:    '0x66d9ef'
    magenta: '0xae81ff'
    cyan:    '0xa1efe4'
    white:   '0xf9f8f5'

  indexed_colors:
    - { index: 16, color: '0xfd971f' }
    - { index: 17, color: '0xcc6633' }
    - { index: 18, color: '0x383830' }
    - { index: 19, color: '0x49483e' }
    - { index: 20, color: '0xa59f85' }
    - { index: 21, color: '0xf5f4f1' }
