# Configuration for Alacritty, the GPU enhanced terminal emulator.

shell:
    program: /usr/bin/bash

window:
    dimensions:
        columns: 89
        lines: 26
    padding:
        x: 25
        y: 20
    decorations: full
    title: Terminal
    dynamic_title: true

background_opacity: 1

font:
    normal:
        family: Iosevka
        style: Medium
    bold:
        style: Bold
    italic:
        style: Medium Italic
    bold_italic:
        style: Bold Italic

    # Test for Greek support:
    #     τὸ γὰρ αὐτὸ νοεῖν ἐστίν τε καὶ εἶναι.

    size: 12
    offset:
        x: 1
        y: 7
    use_thin_strokes: true

key_bindings:
    - { key: H,         mods: alt,       chars: "\x1bh"           }
    - { key: J,         mods: alt,       chars: "\x1bj"           }
    - { key: K,         mods: alt,       chars: "\x1bk"           }
    - { key: L,         mods: alt,       chars: "\x1bl"           }
    - { key: I,         mods: control,   chars: "*"               }

schemes:

    light: &light
        primary:
            background: '0xf8f8f8'
            foreground: '0x383838'
        cursor:
            text: '0xf8f8f8'
            cursor: '0x383838'
        normal:
            black:   '0xf8f8f8'
            red:     '0xab4642'
            green:   '0xa1b56c'
            yellow:  '0xf7ca88'
            blue:    '0x7cafc2'
            magenta: '0xba8baf'
            cyan:    '0x86c1b9'
            white:   '0x383838'
        bright:
            black:   '0xb8b8b8'
            red:     '0xab4642'
            green:   '0xa1b56c'
            yellow:  '0xf7ca88'
            blue:    '0x7cafc2'
            magenta: '0xba8baf'
            cyan:    '0x86c1b9'
            white:   '0x181818'

    monokai: &monokai
        primary:
            # background: '#272825' # default
            background: '#1b1b1b' # a bit darker
            # background: '#312c2b' # coffee
            foreground: '#F8F8F2'
        normal:
            black:   '#272822'
            red:     '#F92672'
            green:   '#A6E22E'
            yellow:  '#F4BF75'
            blue:    '#66D9EF'
            magenta: '#AE81FF'
            cyan:    '#A1EFE4'
            white:   '#F8F8F2'
        bright:
            black:   '#75715E'
            red:     '#F92672'
            green:   '#A6E22E'
            yellow:  '#F4BF75'
            blue:    '#66D9EF'
            magenta: '#AE81FF'
            cyan:    '#A1EFE4'
            white:   '#F9F8F5'

colors: *monokai
