# Configuration for Alacritty, the GPU enhanced terminal emulator.

shell:
    program: /usr/bin/bash

window:
    dimensions:
        columns: 89
        lines: 26
    padding:
        x: 15
        y: 10
    decorations: full
    title: Terminal
    dynamic_title: true

background_opacity: 1

font:
    normal:
        # τὸ γὰρ αὐτὸ νοεῖν ἐστίν τε καὶ εἶναι.
        family: Rec Mono Linear
        style: Regular
    bold:
        style: Bold
    italic:
        style: Italic
    bold_italic:
        style: Bold Italic

    size: 11.5
    offset:
        x: 0
        y: 0
    use_thin_strokes: true

key_bindings:
    - { key: H,         mods: alt,       chars: "\x1bh"           }
    - { key: J,         mods: alt,       chars: "\x1bj"           }
    - { key: K,         mods: alt,       chars: "\x1bk"           }
    - { key: L,         mods: alt,       chars: "\x1bl"           }

schemes:

    estuary: &estuary
        primary:
            background: '0xf4f3ec'
            foreground: '0x5f5e4e'
        cursor:
            text: '0xf4f3ec'
            cursor: '0x5f5e4e'
        normal:
            black:   '0xf4f3ec'
            red:     '0xba6236'
            green:   '0x7d9726'
            yellow:  '0xa5980d'
            blue:    '0x36a166'
            magenta: '0x5f9182'
            cyan:    '0x5b9d48'
            white:   '0x5f5e4e'
        bright:
            black:   '0x878573'
            red:     '0xae7313'
            green:   '0xe7e6df'
            yellow:  '0x929181'
            blue:    '0x6c6b5a'
            magenta: '0x302f27'
            cyan:    '0x9d6c7c'
            white:   '0x22221b'

    sonokai: &sonokai
        primary:
            background: "0x2d2a2e"
            foreground: "0xe3e1e4"
        normal:
            black: "0x1a181a"
            red: "0xf85e84"
            green: "0x9ecd6f"
            yellow: "0xe5c463"
            blue: "0x7accd7"
            magenta: "0xab9df2"
            cyan: "0xef9062"
            white: "0xe3e1e4"
        bright:
            black: "0x1a181a"
            red: "0xf85e84"
            green: "0x9ecd6f"
            yellow: "0xe5c463"
            blue: "0x7accd7"
            magenta: "0xab9df2"
            cyan: "0xef9062"
            white: "0xe3e1e4"

colors: *sonokai
