shell:
  program: /usr/bin/bash
window:
  dimensions:
    columns: 89
    lines: 27
  padding:
    x: 5
    y: 5
  decorations: full
  title: Terminal
  dynamic_title: false
background_opacity: 1
font:
  normal:
    family: Iosevka
    style: Regular
  bold:
    style: Bold
  italic:
    style: Italic
  bold_italic:
    style: Bold Italic
  size: 11
  offset:
    x: 0
    y: 0
  use_thin_strokes: true
cursor:
  style:
    shape: Beam
    blinking: Always
key_bindings:
  - key: H
    mods: alt
    chars: "\eh"
  - key: J
    mods: alt
    chars: "\ej"
  - key: K
    mods: alt
    chars: "\ek"
  - key: L
    mods: alt
    chars: "\el"
  - key: I
    mods: control
    chars: "*"
colors:
  primary:
    background: "#202734"
    foreground: "#CBCCC6"
  normal:
    black: "#191E2A"
    red: "#FF3333"
    green: "#BAE67E"
    yellow: "#FFA759"
    blue: "#73D0FF"
    magenta: "#FFD580"
    cyan: "#95E6CB"
    white: "#C7C7C7"
  bright:
    black: "#686868"
    red: "#F27983"
    green: "#A6CC70"
    yellow: "#FFCC66"
    blue: "#5CCFE6"
    magenta: "#FFEE99"
    cyan: "#95E6CB"
    white: "#FFFFFF"
